version: '3'
services:
  time-tracker-frontend:
    image: hicsail/sail-time-tracker-frontend:latest
    container_name: time-tracker-frontend
    restart: always
    ports:
      - 4000:80
    env_file:
      - ../stack.env
  time-tracker-backend:
    image: hicsail/sail-time-tracker-backend:latest
    container_name: time-tracker-backend
    restart: always
    ports:
      - 4001:3000
    env_file:
      - ../stack.env
  time-tracker-postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - time-tracker-prod:/var/lib/postgresql/data
    env_file:
      - ../stack.env
  backup:
    image: offen/docker-volume-backup:v2.27.0
    restart: always
    env_file:
      - ../backup.env
      - ../stack.env
    volumes:
      - time-tracker-prod:/backup:ro
volumes:
  time-tracker-prod: ~